/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SelectSiteRouteImport } from './routes/select-site'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InviteAcceptRouteImport } from './routes/invite-accept'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppViewerRouteImport } from './routes/_app.viewer'
import { Route as AppSitesRouteImport } from './routes/_app.sites'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppOrganizationSettingsRouteImport } from './routes/_app.organization-settings'
import { Route as AppMembersRouteImport } from './routes/_app.members'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppEmployeesRouteImport } from './routes/_app.employees'
import { Route as AppEditorRouteImport } from './routes/_app.editor'
import { Route as AppAssignmentRouteImport } from './routes/_app.assignment'
import { Route as AppAccountRouteImport } from './routes/_app.account'
import { Route as AppEditorIndexRouteImport } from './routes/_app.editor.index'
import { Route as AppAssignmentIndexRouteImport } from './routes/_app.assignment.index'
import { Route as AppSettingsViewerRouteImport } from './routes/_app.settings.viewer'
import { Route as AppSettingsTagsRouteImport } from './routes/_app.settings.tags'
import { Route as AppSettingsShiftsRouteImport } from './routes/_app.settings.shifts'
import { Route as AppEditorAreaIdRouteImport } from './routes/_app.editor.$areaId'
import { Route as AppAssignmentAreaIdRouteImport } from './routes/_app.assignment.$areaId'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectSiteRoute = SelectSiteRouteImport.update({
  id: '/select-site',
  path: '/select-site',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteAcceptRoute = InviteAcceptRouteImport.update({
  id: '/invite-accept',
  path: '/invite-accept',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppViewerRoute = AppViewerRouteImport.update({
  id: '/viewer',
  path: '/viewer',
  getParentRoute: () => AppRoute,
} as any)
const AppSitesRoute = AppSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationSettingsRoute = AppOrganizationSettingsRouteImport.update({
  id: '/organization-settings',
  path: '/organization-settings',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppEditorRoute = AppEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AppRoute,
} as any)
const AppAssignmentRoute = AppAssignmentRouteImport.update({
  id: '/assignment',
  path: '/assignment',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppEditorIndexRoute = AppEditorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEditorRoute,
} as any)
const AppAssignmentIndexRoute = AppAssignmentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAssignmentRoute,
} as any)
const AppSettingsViewerRoute = AppSettingsViewerRouteImport.update({
  id: '/viewer',
  path: '/viewer',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsTagsRoute = AppSettingsTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsShiftsRoute = AppSettingsShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppEditorAreaIdRoute = AppEditorAreaIdRouteImport.update({
  id: '/$areaId',
  path: '/$areaId',
  getParentRoute: () => AppEditorRoute,
} as any)
const AppAssignmentAreaIdRoute = AppAssignmentAreaIdRouteImport.update({
  id: '/$areaId',
  path: '/$areaId',
  getParentRoute: () => AppAssignmentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite-accept': typeof InviteAcceptRoute
  '/login': typeof LoginRoute
  '/select-site': typeof SelectSiteRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/account': typeof AppAccountRoute
  '/assignment': typeof AppAssignmentRouteWithChildren
  '/editor': typeof AppEditorRouteWithChildren
  '/employees': typeof AppEmployeesRoute
  '/history': typeof AppHistoryRoute
  '/home': typeof AppHomeRoute
  '/members': typeof AppMembersRoute
  '/organization-settings': typeof AppOrganizationSettingsRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/sites': typeof AppSitesRoute
  '/viewer': typeof AppViewerRoute
  '/assignment/$areaId': typeof AppAssignmentAreaIdRoute
  '/editor/$areaId': typeof AppEditorAreaIdRoute
  '/settings/shifts': typeof AppSettingsShiftsRoute
  '/settings/tags': typeof AppSettingsTagsRoute
  '/settings/viewer': typeof AppSettingsViewerRoute
  '/assignment/': typeof AppAssignmentIndexRoute
  '/editor/': typeof AppEditorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite-accept': typeof InviteAcceptRoute
  '/login': typeof LoginRoute
  '/select-site': typeof SelectSiteRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/account': typeof AppAccountRoute
  '/employees': typeof AppEmployeesRoute
  '/history': typeof AppHistoryRoute
  '/home': typeof AppHomeRoute
  '/members': typeof AppMembersRoute
  '/organization-settings': typeof AppOrganizationSettingsRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/sites': typeof AppSitesRoute
  '/viewer': typeof AppViewerRoute
  '/assignment/$areaId': typeof AppAssignmentAreaIdRoute
  '/editor/$areaId': typeof AppEditorAreaIdRoute
  '/settings/shifts': typeof AppSettingsShiftsRoute
  '/settings/tags': typeof AppSettingsTagsRoute
  '/settings/viewer': typeof AppSettingsViewerRoute
  '/assignment': typeof AppAssignmentIndexRoute
  '/editor': typeof AppEditorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/catalog': typeof CatalogRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite-accept': typeof InviteAcceptRoute
  '/login': typeof LoginRoute
  '/select-site': typeof SelectSiteRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/assignment': typeof AppAssignmentRouteWithChildren
  '/_app/editor': typeof AppEditorRouteWithChildren
  '/_app/employees': typeof AppEmployeesRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/members': typeof AppMembersRoute
  '/_app/organization-settings': typeof AppOrganizationSettingsRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/sites': typeof AppSitesRoute
  '/_app/viewer': typeof AppViewerRoute
  '/_app/assignment/$areaId': typeof AppAssignmentAreaIdRoute
  '/_app/editor/$areaId': typeof AppEditorAreaIdRoute
  '/_app/settings/shifts': typeof AppSettingsShiftsRoute
  '/_app/settings/tags': typeof AppSettingsTagsRoute
  '/_app/settings/viewer': typeof AppSettingsViewerRoute
  '/_app/assignment/': typeof AppAssignmentIndexRoute
  '/_app/editor/': typeof AppEditorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/forgot-password'
    | '/invite-accept'
    | '/login'
    | '/select-site'
    | '/signup'
    | '/verify-otp'
    | '/account'
    | '/assignment'
    | '/editor'
    | '/employees'
    | '/history'
    | '/home'
    | '/members'
    | '/organization-settings'
    | '/settings'
    | '/sites'
    | '/viewer'
    | '/assignment/$areaId'
    | '/editor/$areaId'
    | '/settings/shifts'
    | '/settings/tags'
    | '/settings/viewer'
    | '/assignment/'
    | '/editor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/forgot-password'
    | '/invite-accept'
    | '/login'
    | '/select-site'
    | '/signup'
    | '/verify-otp'
    | '/account'
    | '/employees'
    | '/history'
    | '/home'
    | '/members'
    | '/organization-settings'
    | '/settings'
    | '/sites'
    | '/viewer'
    | '/assignment/$areaId'
    | '/editor/$areaId'
    | '/settings/shifts'
    | '/settings/tags'
    | '/settings/viewer'
    | '/assignment'
    | '/editor'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/catalog'
    | '/forgot-password'
    | '/invite-accept'
    | '/login'
    | '/select-site'
    | '/signup'
    | '/verify-otp'
    | '/_app/account'
    | '/_app/assignment'
    | '/_app/editor'
    | '/_app/employees'
    | '/_app/history'
    | '/_app/home'
    | '/_app/members'
    | '/_app/organization-settings'
    | '/_app/settings'
    | '/_app/sites'
    | '/_app/viewer'
    | '/_app/assignment/$areaId'
    | '/_app/editor/$areaId'
    | '/_app/settings/shifts'
    | '/_app/settings/tags'
    | '/_app/settings/viewer'
    | '/_app/assignment/'
    | '/_app/editor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CatalogRoute: typeof CatalogRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InviteAcceptRoute: typeof InviteAcceptRoute
  LoginRoute: typeof LoginRoute
  SelectSiteRoute: typeof SelectSiteRoute
  SignupRoute: typeof SignupRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-site': {
      id: '/select-site'
      path: '/select-site'
      fullPath: '/select-site'
      preLoaderRoute: typeof SelectSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite-accept': {
      id: '/invite-accept'
      path: '/invite-accept'
      fullPath: '/invite-accept'
      preLoaderRoute: typeof InviteAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/viewer': {
      id: '/_app/viewer'
      path: '/viewer'
      fullPath: '/viewer'
      preLoaderRoute: typeof AppViewerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sites': {
      id: '/_app/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AppSitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organization-settings': {
      id: '/_app/organization-settings'
      path: '/organization-settings'
      fullPath: '/organization-settings'
      preLoaderRoute: typeof AppOrganizationSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members': {
      id: '/_app/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/editor': {
      id: '/_app/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof AppEditorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assignment': {
      id: '/_app/assignment'
      path: '/assignment'
      fullPath: '/assignment'
      preLoaderRoute: typeof AppAssignmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/editor/': {
      id: '/_app/editor/'
      path: '/'
      fullPath: '/editor/'
      preLoaderRoute: typeof AppEditorIndexRouteImport
      parentRoute: typeof AppEditorRoute
    }
    '/_app/assignment/': {
      id: '/_app/assignment/'
      path: '/'
      fullPath: '/assignment/'
      preLoaderRoute: typeof AppAssignmentIndexRouteImport
      parentRoute: typeof AppAssignmentRoute
    }
    '/_app/settings/viewer': {
      id: '/_app/settings/viewer'
      path: '/viewer'
      fullPath: '/settings/viewer'
      preLoaderRoute: typeof AppSettingsViewerRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/tags': {
      id: '/_app/settings/tags'
      path: '/tags'
      fullPath: '/settings/tags'
      preLoaderRoute: typeof AppSettingsTagsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/shifts': {
      id: '/_app/settings/shifts'
      path: '/shifts'
      fullPath: '/settings/shifts'
      preLoaderRoute: typeof AppSettingsShiftsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/editor/$areaId': {
      id: '/_app/editor/$areaId'
      path: '/$areaId'
      fullPath: '/editor/$areaId'
      preLoaderRoute: typeof AppEditorAreaIdRouteImport
      parentRoute: typeof AppEditorRoute
    }
    '/_app/assignment/$areaId': {
      id: '/_app/assignment/$areaId'
      path: '/$areaId'
      fullPath: '/assignment/$areaId'
      preLoaderRoute: typeof AppAssignmentAreaIdRouteImport
      parentRoute: typeof AppAssignmentRoute
    }
  }
}

interface AppAssignmentRouteChildren {
  AppAssignmentAreaIdRoute: typeof AppAssignmentAreaIdRoute
  AppAssignmentIndexRoute: typeof AppAssignmentIndexRoute
}

const AppAssignmentRouteChildren: AppAssignmentRouteChildren = {
  AppAssignmentAreaIdRoute: AppAssignmentAreaIdRoute,
  AppAssignmentIndexRoute: AppAssignmentIndexRoute,
}

const AppAssignmentRouteWithChildren = AppAssignmentRoute._addFileChildren(
  AppAssignmentRouteChildren,
)

interface AppEditorRouteChildren {
  AppEditorAreaIdRoute: typeof AppEditorAreaIdRoute
  AppEditorIndexRoute: typeof AppEditorIndexRoute
}

const AppEditorRouteChildren: AppEditorRouteChildren = {
  AppEditorAreaIdRoute: AppEditorAreaIdRoute,
  AppEditorIndexRoute: AppEditorIndexRoute,
}

const AppEditorRouteWithChildren = AppEditorRoute._addFileChildren(
  AppEditorRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsShiftsRoute: typeof AppSettingsShiftsRoute
  AppSettingsTagsRoute: typeof AppSettingsTagsRoute
  AppSettingsViewerRoute: typeof AppSettingsViewerRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsShiftsRoute: AppSettingsShiftsRoute,
  AppSettingsTagsRoute: AppSettingsTagsRoute,
  AppSettingsViewerRoute: AppSettingsViewerRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAssignmentRoute: typeof AppAssignmentRouteWithChildren
  AppEditorRoute: typeof AppEditorRouteWithChildren
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppHomeRoute: typeof AppHomeRoute
  AppMembersRoute: typeof AppMembersRoute
  AppOrganizationSettingsRoute: typeof AppOrganizationSettingsRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppSitesRoute: typeof AppSitesRoute
  AppViewerRoute: typeof AppViewerRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAssignmentRoute: AppAssignmentRouteWithChildren,
  AppEditorRoute: AppEditorRouteWithChildren,
  AppEmployeesRoute: AppEmployeesRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppHomeRoute: AppHomeRoute,
  AppMembersRoute: AppMembersRoute,
  AppOrganizationSettingsRoute: AppOrganizationSettingsRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppSitesRoute: AppSitesRoute,
  AppViewerRoute: AppViewerRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CatalogRoute: CatalogRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InviteAcceptRoute: InviteAcceptRoute,
  LoginRoute: LoginRoute,
  SelectSiteRoute: SelectSiteRoute,
  SignupRoute: SignupRoute,
  VerifyOtpRoute: VerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
